server:
  port: 8888
spring:
  application:
    name: mall-gateway
  #\u914D\u7F6Enacos\u6CE8\u518C\u4E2D\u5FC3\u5730\u5740
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    gateway:
      discovery:
        locator:
          # \u9ED8\u8BA4\u4E3Afalse\uFF0C\u8BBE\u4E3Atrue\u5F00\u542F\u901A\u8FC7\u5FAE\u670D\u52A1\u521B\u5EFA\u8DEF\u7531\u7684\u529F\u80FD\uFF0C\u5373\u53EF\u4EE5\u901A\u8FC7\u5FAE\u670D\u52A1\u540D\u8BBF\u95EE\u670D\u52A1
          # http://localhost:8888/mall-order/order/findOrderByUserId/1
          enabled: false
      # \u662F\u5426\u5F00\u542F\u7F51\u5173
      enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTION

      #\u8BBE\u7F6E\u8DEF\u7531\uFF1A\u8DEF\u7531id\u3001\u8DEF\u7531\u5230\u5FAE\u670D\u52A1\u7684uri\u3001\u65AD\u8A00
      routes:
        - id: order_route  #\u8DEF\u7531ID\uFF0C\u5168\u5C40\u552F\u4E00\uFF0C\u5EFA\u8BAE\u914D\u5408\u670D\u52A1\u540D
          #        #uri: http://localhost:8020  #\u76EE\u6807\u5FAE\u670D\u52A1\u7684\u8BF7\u6C42\u5730\u5740\u548C\u7AEF\u53E3
          uri: lb://mall-order  #lb \u6574\u5408\u8D1F\u8F7D\u5747\u8861\u5668ribbon,loadbalancer
          predicates:
            #        #Path\u8DEF\u5F84\u5339\u914D
            - Path=/order/**
          # \u6D4B\u8BD5 http://localhost:8888/order/findOrderByUserId/1
          # \u5339\u914D\u5728\u6307\u5B9A\u7684\u65E5\u671F\u65F6\u95F4\u4E4B\u540E\u53D1\u751F\u7684\u8BF7\u6C42  \u5165\u53C2\u662FZonedDateTime\u7C7B\u578B
          #- After=2021-05-16T20:50:57.511+08:00[Asia/Shanghai]
          # Cookie\u5339\u914D
          #- Cookie=username, fox
          # Header\u5339\u914D  \u8BF7\u6C42\u4E2D\u5E26\u6709\u8BF7\u6C42\u5934\u540D\u4E3A x-request-id\uFF0C\u5176\u503C\u4E0E \d+ \u6B63\u5219\u8868\u8FBE\u5F0F\u5339\u914D
          #- Header=X-Request-Id, \d+
          #\u81EA\u5B9A\u4E49CheckAuth\u65AD\u8A00\u5DE5\u5382
          #        - name: CheckAuth
          #          args:
          #            name: fox
          #- CheckAuth=monkey
          #\u914D\u7F6E\u8FC7\u6EE4\u5668\u5DE5\u5382
          filters:
            - AddRequestHeader=X-Request-color, red  #\u6DFB\u52A0\u8BF7\u6C42\u5934
            - AddRequestParameter=color, blue   # \u6DFB\u52A0\u8BF7\u6C42\u53C2\u6570
            - PrefixPath=/mall-order  # \u6DFB\u52A0\u524D\u7F00 \u5BF9\u5E94\u5FAE\u670D\u52A1\u9700\u8981\u914D\u7F6Econtext-path
            #- RedirectTo=302, http://baidu.com  #\u91CD\u5B9A\u5411\u5230\u767E\u5EA6
            - CheckAuth=fox,\u7537  #\u914D\u7F6E\u81EA\u5B9A\u4E49\u7684\u8FC7\u6EE4\u5668\u5DE5\u5382

        - id: user_route
          uri: lb://mall-user  #lb \u6574\u5408\u8D1F\u8F7D\u5747\u8861\u5668ribbon,loadbalancer
          predicates:
            - Path=/user/**






